export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const REQUESTED = "REQUESTED";
export const SUCCESS = "SUCCESS";
export const FAILED = "FAILED";
export const LOAD_EMOJIES_REQUESTED = "LOAD_EMOJIES_REQUESTED";
export const LOAD_EMOJIES_SUCCESS = "LOAD_EMOJIES_SUCCESS";
export const LOAD_EMOJIES_FAIL = "LOAD_EMOJIES_FAIL";
